title: "jni++"
author:
  name: Tom Micheline
  email: tom@tmich.dev
description: "C++ JNI without the boilerplate"

# Build settings
remote_theme: pages-themes/cayman
exclude: ["CMakeLists.txt"]

show_downloads: false
